name: No PR

on:
  pull_request:
    types: [opened]

jobs:
  close_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Close PR
        run: gh pr close ${{ github.event.pull_request.number }} -d "This repository does not accept pull requests" -d
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
